name: hola_mundo

on:                    #que desencadena el workflow
  workflow_dispatch:  #ejecucion manual
  #push: 
  #  branches:         #que ramas  deben ser actualizadas para ejecutar este bransh
  #    - main
  #  paths:          # que rutas del proyecto que si se modifican, implican correr lo siguiente
  #    - 'BibliotecaAPI/**'
  #    - 'BibliotecaApiTest/**'
  #    - '.github/workflows/hola_mundo.yml'
  #pull_request:
  #   branches:        
  #    - main

jobs:
  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: muestra mensaje hola mundo
        run: echo "hola mundo fer"

      - name: checkout
        uses: actions/checkout@v6.0.2

      - name: listar archivos del repo
        run: |
          echo "El repositorio ${{github.repository}} contiene los siguientes archivos:"
          tree
        
  
